/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puk.vista;

import puk.modelo.GestionBiblioteca;
import javax.swing.table.DefaultTableModel;
import puk.modelo.Libro;
import puk.persistencia.PersistenciaBiblioteca;
import java.util.ArrayList;

/**
 *
 * @author utpuk
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    private GestionBiblioteca biblioteca;
    private PersistenciaBiblioteca persistencia;

    public VentanaPrincipal(
            GestionBiblioteca biblioteca,
            PersistenciaBiblioteca persistencia) {

        initComponents();

        this.biblioteca = biblioteca;
        this.persistencia = persistencia;

        bloquearEdicionTabla();
        cargarTabla();
        ajustarColumnas();

        setLocationRelativeTo(null);
    }

    public void cargarTabla() {

        cargarLibrosEnTabla(biblioteca.getLibros());
         actualizarTotalLibros();
    }

    private void actualizarTotalLibros() {

        lblTotalLibros.setText(
                "Total de libros: "
                + biblioteca.getLibros().size()
        );

    }

    private void cargarLibrosEnTabla(ArrayList<Libro> libros) {

        DefaultTableModel modelo
                = (DefaultTableModel) tablaLibros.getModel();

        modelo.setRowCount(0);

        for (Libro libro : libros) {

            Object[] fila = {
                libro.getId(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getIsbn(),
                libro.getAnioPublicacion(),
                libro.isOriginal() ? "Original" : "Fotocopia",
                libro.isFisico() ? "Físico" : "Digital"
            };

            modelo.addRow(fila);
        }
    }

    private void ajustarColumnas() {
        tablaLibros.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaLibros.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablaLibros.getColumnModel().getColumn(2).setPreferredWidth(160);
        tablaLibros.getColumnModel().getColumn(3).setPreferredWidth(130);
        tablaLibros.getColumnModel().getColumn(4).setPreferredWidth(90);
        tablaLibros.getColumnModel().getColumn(5).setPreferredWidth(90);
        tablaLibros.getColumnModel().getColumn(6).setPreferredWidth(90);
    }

    private void bloquearEdicionTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID",
                    "Título",
                    "Autor",
                    "ISBN",
                    "Año publicación",
                    "Original",
                    "Formato"
                }
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        tablaLibros.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        scrollTablaLibros = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnNuevoLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTotalLibros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Biblioteca de Puk");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor", "ISBN", "Año publicación", "Original", "Formato"
            }
        ));
        scrollTablaLibros.setViewportView(tablaLibros);

        btnNuevoLibro.setText("Nuevo libro");
        btnNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar libro");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        txtBuscar.setText("Buscar...");
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblTotalLibros.setText("Total del libros: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablaLibros)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnNuevoLibro)
                        .addGap(42, 42, 42)
                        .addComponent(btnEliminarLibro)
                        .addGap(36, 36, 36)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoLibro)
                    .addComponent(btnEliminarLibro)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLibroActionPerformed
        VentanaNuevoLibro ventana
                = new VentanaNuevoLibro(
                        biblioteca,
                        persistencia,
                        this
                );

        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        int filaSeleccionada = tablaLibros.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Selecciona un libro de la tabla.",
                    "Ningún libro seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int id = Integer.parseInt(
                tablaLibros.getValueAt(filaSeleccionada, 0).toString()
        );

        String titulo = tablaLibros
                .getValueAt(filaSeleccionada, 1)
                .toString();

        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas eliminar \"" + titulo + "\"?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (respuesta != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        String mensaje = biblioteca.eliminarLibro(id);

        persistencia.guardar(biblioteca);

        cargarTabla();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Libro eliminado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String texto = txtBuscar.getText().trim();

        if (texto.isEmpty()) {
            cargarTabla();
            return;
        }

        cargarLibrosEnTabla(
                biblioteca.buscarLibros(texto)
        );

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        if (txtBuscar.getText().equals("Buscar...")) {
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBuscar.setText("Buscar...");
        cargarTabla();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevoLibro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalLibros;
    private javax.swing.JScrollPane scrollTablaLibros;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
