/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puk.vista;

import puk.modelo.GestionBiblioteca;
import javax.swing.table.DefaultTableModel;
import puk.modelo.Libro;
import puk.persistencia.PersistenciaBiblioteca;

/**
 *
 * @author utpuk
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    private GestionBiblioteca biblioteca;
    private PersistenciaBiblioteca persistencia;

    public VentanaPrincipal(
            GestionBiblioteca biblioteca,
            PersistenciaBiblioteca persistencia) {

        initComponents();

        this.biblioteca = biblioteca;
        this.persistencia = persistencia;

        bloquearEdicionTabla();
        cargarTabla();
        ajustarColumnas();

        setLocationRelativeTo(null);
    }

    public void cargarTabla() {

        DefaultTableModel modelo
                = (DefaultTableModel) tablaLibros.getModel();

        modelo.setRowCount(0);

        for (Libro libro : biblioteca.getLibros()) {

            Object[] fila = {
                libro.getId(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getIsbn(),
                libro.getAnioPublicacion(),
                libro.isOriginal() ? "Original" : "Fotocopia",
                libro.isFisico() ? "Físico" : "Digital"
            };

            modelo.addRow(fila);
        }
    }

    private void ajustarColumnas() {
        tablaLibros.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaLibros.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablaLibros.getColumnModel().getColumn(2).setPreferredWidth(160);
        tablaLibros.getColumnModel().getColumn(3).setPreferredWidth(130);
        tablaLibros.getColumnModel().getColumn(4).setPreferredWidth(90);
        tablaLibros.getColumnModel().getColumn(5).setPreferredWidth(90);
        tablaLibros.getColumnModel().getColumn(6).setPreferredWidth(90);
    }

    private void bloquearEdicionTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID",
                    "Título",
                    "Autor",
                    "ISBN",
                    "Año publicación",
                    "Original",
                    "Formato"
                }
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        tablaLibros.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        scrollTablaLibros = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnNuevoLibro = new javax.swing.JButton();
        btnEditarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Biblioteca de Puk");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor", "ISBN", "Año publicación", "Original", "Formato"
            }
        ));
        scrollTablaLibros.setViewportView(tablaLibros);

        btnNuevoLibro.setText("Nuevo libro");
        btnNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLibroActionPerformed(evt);
            }
        });

        btnEditarLibro.setText("Editar libro");
        btnEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar libro");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTablaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevoLibro)
                        .addGap(46, 46, 46)
                        .addComponent(btnEditarLibro)
                        .addGap(35, 35, 35)
                        .addComponent(btnEliminarLibro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoLibro)
                    .addComponent(btnEditarLibro)
                    .addComponent(btnEliminarLibro))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLibroActionPerformed
        VentanaNuevoLibro ventana
                = new VentanaNuevoLibro(
                        biblioteca,
                        persistencia,
                        this
                );

        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLibro;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnNuevoLibro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollTablaLibros;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
}
